version: '3.9'

services:

  postgres:
    image: postgres:16
    container_name: ledger-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ledgerdb
    ports:
      - "5432:5432"
    volumes:
      - ledger-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d ledgerdb"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: ledger-zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: ledger-kafka
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://ledger-kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: ledger-kafka-ui
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: ledger-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: ledger-kafka:9092
      # opcional: tabela de offsets, prover estados
      KAFKA_CLUSTERS_0_ZOOKEEPER: ledger-zookeeper:2181

volumes:
  ledger-data:
